<?xml version="1.0"?>
<grammar xmlns="http://relaxng.org/ns/structure/1.0" datatypeLibrary="http://www.w3.org/2001/XMLSchema-datatypes"><start><ref name="profile"/></start><define name="profile"><element name="profile"><attribute name="name"><data type="string"/></attribute><attribute name="organization"><data type="string"><param name="pattern">[a-zA-Z0-9_.-]+</param></data></attribute><attribute name="application"><data type="string"><param name="pattern">[a-zA-Z0-9_.-]+</param></data></attribute><attribute name="version"><data type="string"/></attribute><optional><externalRef href="http://city-occupational.co.uk/relaxng/registry/1.0/registry-1.0.rng"/></optional></element></define></grammar>
